name: hello
on: [push]

jobs:
  build:
    name: hello
    runs-on: ubuntu-latest
    steps:
    - name: hello-step
      run: echo "hello from actions"
    - name: test-docker
      run: docker ps -a
    - name: Check out repository
      uses: actions/checkout@v2
    - name: with-custom-image
      uses: ./.github/actions/with-python

