name: hello
on: [push]

jobs:
  build:
    name: hello
    runs-on: ubuntu-latest
    steps:
    - name: hello-step
      run: echo "hello from actions"
    - name: test-docker
      run: docker ps -a
    - name: Check out repository
      uses: actions/checkout@v2
    - name: with-custom-image
      uses: ./.github/actions/with-python
  another-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim
    steps:
    - name: toto
      run: python --version
  third-one:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: testing things
      uses: ./.github/actions/testing-content
    - name: testing things 2
      uses: ./.github/actions/testing-content
