name: hello
on: [push]

jobs:
  build:
    name: hello
    runs-on: ubuntu-latest
    steps:
    - name: hello-step
      run: echo "hello from actions"
    - name: test-docker
      run: docker ps -a
    - name: with-custom-image
      uses: docker://python:3.8-slim
      run: python --version
